create components folder, put app.js + app.css in it
zinagithub/calculator-tool pull request #5
Opened 2019-10-07 11:09 UTC by zinagithub

2019-10-08 10:31 UTC, SunnyAsar requested changes
# Hi @zinagithub 👋 
### Wonderful work!
- to call it done, i have pointed out some missed requirement, please make these update.
- Also remember to always but a summary of what you have done as the description of the pull request.
- in the comments are the pointers.

**Please request another code review when the update is done**
cheers!

2019-10-08 10:31 UTC, SunnyAsar commented on src/components/Display.js
> +    }
* [ ] it accepts the result of the calculation as an incoming prop
 * [ ] its result prop should be a String with default value = 0
 Hi, as stated by our requirements,:
- result is coming a prop, so you don't need it in  state.
- and when its not there,  use defaultProps to set a valule of `'0'`

2019-10-08 10:31 UTC, SunnyAsar commented on src/components/Display.js
> +         <p> {this.state.result} </p>
this should be from props not state

2019-10-08 10:31 UTC, SunnyAsar commented on src/components/Button.js
> +         <button className = 'butCal'> {this.props.value} </button>
setup propTypes and require the button name coming in props is a string [REQUIRED]

2019-10-08 10:31 UTC, SunnyAsar commented on src/components/ButtonPanel.js
> +                  '4', '5', '6', '-',
Hey, this is not gonna change, we don't necessarily need it in state, it can just be an array in render.

2019-10-08 10:31 UTC, SunnyAsar commented on src/components/ButtonPanel.js
> +             return (<Button value = {elm}  />)
react requires list of things to have a key, in this case you can use the index of the item as the key.

2019-10-09 18:25 UTC, BalintMendli requested changes
Hi @zinagithub ,

Great job so far. 👏 

However, we're still missing some requirements for this milestone:

#### propTypes

Let's set up [propTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) to validate the props in Display and Button components:
* Display should have a result prop which is a string with a default value of '0'
* Button should have a name prop which is a string and is required

In order to do this we need to install the [prop-types](https://www.npmjs.com/package/prop-types) package.

#### List keys

Let's use key's for our mapped components. See my comment below.

[Optional] Display, ButtonPanel and Button can be stateless functional components as we won't have state in them.

Also there are 2 `+` on the calculator and no `/`. Please fix it.

**Please update the app and submit another review request.**

_If you have any questions do not hesitate to contact me on Slack._

2019-10-09 18:25 UTC, zenott commented on src/components/ButtonPanel.js
> +             return (<Button value = {elm}  />)
As @SunnyAsar mentioned, lists in react need to have a unique `key` property in order to identify them for performance reasons. See [docs](https://reactjs.org/docs/lists-and-keys.html#keys). 
So let's add a `key` prop to the mapped component.

2019-10-10 13:19 UTC, BalintMendli requested changes
Hi @zinagithub ,

Great work. 

But let's get propTypes validation straight before moving on:
- Let's validate Button's value prop: it should be a string and should be required
- Display's result prop shouldn't be required as we've set up a default value for it.

**Please make these changes and submit a final review request for the milestone.**

2019-10-10 15:59 UTC, BalintMendli approved these changes
Hi @zinagithub ,

All good.

### 👍 

Let's move to the next milestone. ⏩

2019-10-10 17:46 UTC, merged